/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 *
 * @author dudan
 */
public class Genio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Genio.class.getName());

    /**
     * Creates new form Genio
     */
    public Genio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnpalpite = new javax.swing.JSpinner();
        btnpalpite = new javax.swing.JButton();
        lblakinatormessage = new javax.swing.JLabel();
        lblakinatorimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnpalpite.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spnpalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 310, 80, -1));

        btnpalpite.setText("Palpite");
        btnpalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(btnpalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        lblakinatormessage.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblakinatormessage.setText("Vou pensar em um numero entre 1 e 5 e você adivinha");
        lblakinatormessage.setToolTipText("");
        getContentPane().add(lblakinatormessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 240, 150));

        lblakinatorimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/kindpng_4647448.png"))); // NOI18N
        lblakinatorimage.setText("jLabel1");
        getContentPane().add(lblakinatorimage, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpalpiteActionPerformed
       
        int random = (int) (Math.random() * 5) + 1;
        int palpite = (Integer) spnpalpite.getValue();
        
        if (random == palpite){
            lblakinatormessage.setText("Você acertou, meu numero era o " + random);
        }else{
            lblakinatormessage.setText("Você errou, meu numero era o " + random);
        }
        
    }//GEN-LAST:event_btnpalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Genio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpalpite;
    private javax.swing.JLabel lblakinatorimage;
    private javax.swing.JLabel lblakinatormessage;
    private javax.swing.JSpinner spnpalpite;
    // End of variables declaration//GEN-END:variables
}
