/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09;

import javax.swing.JOptionPane;

/**
 *
 * @author dudan
 */
public class viewEncapsulamento extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(viewEncapsulamento.class.getName());

    /**
     * Creates new form viewEncapsulamento
     */
    public viewEncapsulamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblinformevalor = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        lblpagamento = new javax.swing.JLabel();
        cmbpagamentos = new javax.swing.JComboBox<>();
        btnpagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblinformevalor.setText("Informe o valor a pagar");

        txtvalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalorActionPerformed(evt);
            }
        });

        lblpagamento.setText("Informe o método de pagamento");

        cmbpagamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARTÃO", "DINHEIRO", "PIX" }));
        cmbpagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpagamentosActionPerformed(evt);
            }
        });

        btnpagar.setText("Pagar");
        btnpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblinformevalor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblpagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbpagamentos, 0, 203, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(btnpagar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinformevalor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbpagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnpagar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvalorActionPerformed

    private void btnpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpagarActionPerformed

        Pagamento pagamento = null;

        // Pega o item selecionado no ComboBox
        String tipoPagamento = cmbpagamentos.getSelectedItem().toString();

        // Variável para armazenar o valor
        double valorCompra;

        try {
            // Trata a conversão de String para Double
            valorCompra = Double.parseDouble(txtvalor.getText());

            // Lógica de decisão para criar o objeto correto
            if (tipoPagamento.equalsIgnoreCase("CARTÃO")) {
                PagamentoCartao cartao = new PagamentoCartao();
                cartao.setValor(valorCompra);
                pagamento = cartao;

            } else if (tipoPagamento.equalsIgnoreCase("PIX")) {
                PagamentoPix pix = new PagamentoPix();
                pix.setValor(valorCompra);
                pagamento = pix; // Associa a referência da interface

            } else if (tipoPagamento.equalsIgnoreCase("DINHEIRO")) {
                PagamentoDinheiro dinheiro = new PagamentoDinheiro();
                dinheiro.setValor(valorCompra);
                pagamento = dinheiro; // Associa a referência da interface
            }

            // Exibe o Recibo (Se o objeto de pagamento foi criado com sucesso)
            if (pagamento != null) {
                // Chama o método que calcula o total e retorna a string do recibo
                String recibo = "Valor Total: R$ " + String.format("%.2f", pagamento.calcularTotal()) + "\n\n"
                        + pagamento.imprimirRecibo();

                // Exibe o pop-up com o recibo
                JOptionPane.showMessageDialog(this, recibo, "Recibo de Pagamento", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (NumberFormatException ex) {
            // Trata erro caso o valor não seja um número
            JOptionPane.showMessageDialog(this, "Erro: Informe um valor numérico válido para a compra.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnpagarActionPerformed

    private void cmbpagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpagamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbpagamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new viewEncapsulamento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnpagar;
    private javax.swing.JComboBox<String> cmbpagamentos;
    private javax.swing.JLabel lblinformevalor;
    private javax.swing.JLabel lblpagamento;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
