/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.dao.CursoDao;
import br.com.ifba.curso.dao.CursoIDao;
import br.com.ifba.curso.entity.Curso; // Importa a Entidade (o "molde" dos dados).
import javax.swing.JOptionPane;

/**
 *
 * @author dudan
 */
public class CursoEditar extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CursoEditar.class.getName());

    private Curso cursoParaEditar;

    /**
     * Creates new form CursoEditar
     */
    public CursoEditar(java.awt.Frame parent, boolean modal, Curso curso) {
        super(parent, modal); // Chama o construtor do JDialog
        initComponents();

        // 1. Salva o objeto 'curso' que recebemos como PARÂMETRO
        this.cursoParaEditar = curso;

        // 2. Preenche os campos da tela
        preencherCampos();

        // 3. Centraliza a tela
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarcurso = new javax.swing.JButton();
        txtCodigoedit = new javax.swing.JTextField();
        lblCodigoedit = new javax.swing.JLabel();
        txtNomeedit = new javax.swing.JTextField();
        lblNomeedit = new javax.swing.JLabel();
        lblEditarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEditarcurso.setText("Editar curso");
        btnEditarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarcursoActionPerformed(evt);
            }
        });

        lblCodigoedit.setText("Insira o novo codigo do curso");

        txtNomeedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeeditActionPerformed(evt);
            }
        });

        lblNomeedit.setText("Insira o novo nome do curso");

        lblEditarCurso.setText("EDITANDO CURSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodigoedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeedit)
                    .addComponent(txtCodigoedit))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnEditarcurso)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigoedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarcurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarcursoActionPerformed
// 1. Pega o NOVO nome que o usuário digitou
        String novoNome = txtNomeedit.getText();

        // 2. Validação simples (vê se o campo não está vazio)
        if (novoNome.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "O nome do curso não pode ficar em branco.",
                    "Erro de Validação",
                    JOptionPane.WARNING_MESSAGE);
            return; // Para a execução
        }
        // 3. Atualiza o objeto 'cursoParaEditar' que está na memória
        this.cursoParaEditar.setNome(novoNome);
        // (Não precisamos mexer no código, pois ele não mudou)

        // 4. Tenta salvar a atualização no banco de dados
        try {
            // 5. Cria o DAO
            CursoIDao cursoDAO = new CursoDao();

            // 6. Chama o novo método ATUALIZAR
            cursoDAO.atualizar(this.cursoParaEditar);

            // 7. Se deu certo, mostra mensagem de sucesso
            JOptionPane.showMessageDialog(this,
                    "Curso atualizado com sucesso!",
                    "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);

            // 8. FECHA esta tela (JDialog)
            //    Isso fará o código na 'CursoListar' (no btnEditar) continuar
            //    e atualizar a tabela.
            this.dispose();

        } catch (Exception e) {
            // 9. Se o DAO deu erro (ex: nome duplicado, erro de banco)
            JOptionPane.showMessageDialog(this,
                    "Falha ao atualizar o curso: " + e.getMessage(),
                    "Erro de Banco de Dados",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarcursoActionPerformed

    private void txtNomeeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeeditActionPerformed

    private void preencherCampos() {
        if (this.cursoParaEditar != null) {
            txtNomeedit.setText(this.cursoParaEditar.getNome());
            txtCodigoedit.setText(this.cursoParaEditar.getCodigoCurso());
            txtCodigoedit.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Cria um "pai" e um "curso" falsos só para o 'main' funcionar
            Curso cursoFalso = new Curso();
            cursoFalso.setNome("Curso de Teste");
            cursoFalso.setCodigoCurso("TST01");

            CursoEditar dialog = new CursoEditar(new javax.swing.JFrame(), true, cursoFalso);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarcurso;
    private javax.swing.JLabel lblCodigoedit;
    private javax.swing.JLabel lblEditarCurso;
    private javax.swing.JLabel lblNomeedit;
    private javax.swing.JTextField txtCodigoedit;
    private javax.swing.JTextField txtNomeedit;
    // End of variables declaration//GEN-END:variables
}
