/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.curso.view;

import br.com.ifba.curso.entity.Curso; // Entidade que está sendo editada
import javax.swing.JOptionPane;
import br.com.ifba.curso.controller.CursoIController; // Interface do Controller (o Garçom)

/**
 * CLASSE VIEW (TELA DE EDIÇÃO) * Função: Receber um objeto de Curso existente,
 * permitir a alteração e mandar atualizar. * Analogia: O Formulário de Correção
 * de Dados.
 */
public class CursoEditar extends javax.swing.JDialog {

// Variáveis que vão guardar os dados e o Garçom para trabalhar
    private Curso cursoParaEditar;
    private CursoIController cursoController;

    /**
     * CONSTRUTOR MODIFICADO * Função: Receber todos os dados necessários de
     * quem chamou a tela. * 4 PARÂMETROS: (Pai, Se é modal, O Curso, O
     * Controller)
     */
    public CursoEditar(java.awt.Frame parent, boolean modal, Curso curso, CursoIController controller) {
        super(parent, modal);
        initComponents();

        // 1. Guarda o objeto 'Curso' que veio do banco.
        // Ele tem o ID, o nome antigo, o código antigo, etc.
        this.cursoParaEditar = curso;

        // 2. Guarda o Controller que veio da tela principal (Injeção Manual).
        this.cursoController = controller;

        // 3. Preenche a tela com os dados atuais do objeto.
        preencherCampos();

        // 4. Centraliza a tela em relação à janela principal.
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEditarcurso = new javax.swing.JButton();
        txtCodigoedit = new javax.swing.JTextField();
        lblCodigoedit = new javax.swing.JLabel();
        txtNomeedit = new javax.swing.JTextField();
        lblNomeedit = new javax.swing.JLabel();
        lblEditarCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnEditarcurso.setText("Editar curso");
        btnEditarcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarcursoActionPerformed(evt);
            }
        });

        lblCodigoedit.setText("Insira o novo codigo do curso");

        txtNomeedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeeditActionPerformed(evt);
            }
        });

        lblNomeedit.setText("Insira o novo nome do curso");

        lblEditarCurso.setText("EDITANDO CURSO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEditarCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNomeedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodigoedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeedit)
                    .addComponent(txtCodigoedit))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btnEditarcurso)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEditarCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigoedit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigoedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditarcurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * MÉTODO DO BOTÃO "EDITAR CURSO" * Função: Coletar os novos dados,
     * atualizar o objeto na memória e mandar salvar.
     */
    private void btnEditarcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarcursoActionPerformed
        // 1. Pega o NOVO nome do campo de texto
        String novoNome = txtNomeedit.getText();

        // ** (Faltaria aqui a validação de campo vazio, que o Service fará) **
        // this.cursoParaEditar.setNome(novoNome); // Linha já abaixo
        // 2. Atualiza o objeto 'cursoParaEditar' na memória com o novo nome.
        // O código do curso (chave primária) NÃO deve ser alterado.
        this.cursoParaEditar.setNome(novoNome);

        // 3. Chama a lógica de atualização.
        try {
            // PONTO CHAVE: Usamos o método 'atualizar'.
            // Por quê? Porque 'cursoParaEditar' já existe no banco (tem ID).
            // Se usássemos 'salvar', o Hibernate daria erro de "detached entity".
            this.cursoController.atualizar(this.cursoParaEditar); // <--- ATUALIZAR (MERGE)

            // SUCESSO
            JOptionPane.showMessageDialog(this, "Curso atualizado com sucesso!");

            // Fecha a janela. O código na 'CursoListar' continua e atualiza a tabela.
            this.dispose();

        } catch (Exception e) {
            // FALHA: Captura erros de validação (do Service) ou de banco de dados (DAO).
            JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarcursoActionPerformed

    private void txtNomeeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeeditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeeditActionPerformed

    private void preencherCampos() {
        if (this.cursoParaEditar != null) {
            txtNomeedit.setText(this.cursoParaEditar.getNome());
            txtCodigoedit.setText(this.cursoParaEditar.getCodigoCurso());
            // Bloqueamos a edição do código para garantir que a chave primária
            // da tabela não seja alterada (regra de negócio comum).
            txtCodigoedit.setEnabled(false);
        }
    }

    /**
     * @param args the command line arguments
     */
// --- BLOCO MAIN (APENAS PARA TESTE VISUAL) ---
    public static void main(String args[]) {
        // ... (código do LookAndFeel) ...
        java.awt.EventQueue.invokeLater(() -> {
            // Cria um objeto falso para a tela ter o que mostrar no modo de teste.
            Curso cursoFalso = new Curso();
            cursoFalso.setNome("Curso de Teste");
            cursoFalso.setCodigoCurso("TST01");

            // Passamos 'null' para o controller, pois o Spring não está ligado.
            CursoEditar dialog = new CursoEditar(new javax.swing.JFrame(), true, cursoFalso, null);
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarcurso;
    private javax.swing.JLabel lblCodigoedit;
    private javax.swing.JLabel lblEditarCurso;
    private javax.swing.JLabel lblNomeedit;
    private javax.swing.JTextField txtCodigoedit;
    private javax.swing.JTextField txtNomeedit;
    // End of variables declaration//GEN-END:variables
}
