/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.atividade07.view;

import br.com.ifba.atividade07.classe.ContaBanco;
import javax.swing.JOptionPane;

/**
 *
 * @author dudan
 */
public class AbrirConta extends javax.swing.JDialog {

    private ContaBanco novaConta = null; // Armazena o objeto criado nessa tela

    public ContaBanco getContaCriada() { // metodo para retonar essa conta para a outra tela
        return this.novaConta;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AbrirConta.class.getName());

    /**
     * Creates new form AbrirConta
     */
    public AbrirConta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblinformenome = new javax.swing.JLabel();
        txtabrircontanome = new javax.swing.JTextField();
        lblabrircontatipo = new javax.swing.JLabel();
        txtabrircontatipo = new javax.swing.JTextField();
        btncriarcontaconfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblinformenome.setText("Informe seu nome");

        txtabrircontanome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabrircontanomeActionPerformed(evt);
            }
        });

        lblabrircontatipo.setText("Infome o tipo da conta");

        btncriarcontaconfirmar.setText("Criar conta");
        btncriarcontaconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncriarcontaconfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblinformenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtabrircontanome, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblabrircontatipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtabrircontatipo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(btncriarcontaconfirmar)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinformenome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtabrircontanome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblabrircontatipo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtabrircontatipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncriarcontaconfirmar)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncriarcontaconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncriarcontaconfirmarActionPerformed

        ContaBanco contabanco = new ContaBanco(); // cria o objeto banco
        String nomeDono = txtabrircontanome.getText(); // pega o valor do text field e armazena o nome
        String tipoContaInput = txtabrircontatipo.getText(); //variavel auxiliar apenas que pega o valor do input
        String tipoConta = tipoContaInput.toUpperCase(); // coloca o valor da varivel aux como maiuscula e seta na variavel certa

        //testa de so tem 2 letras e se é CP ou CC
        if (tipoConta.length() != 2 || (!tipoConta.equals("CC") && !tipoConta.equals("CP"))) {
            // Exibe uma mensagem de erro para o usuário caso essa condição nao passe
            JOptionPane.showMessageDialog(this,
                    "O tipo de conta deve ser 'CC' ou 'CP'. Verifique a digitação.",
                    "Erro de Validação",
                    JOptionPane.ERROR_MESSAGE);
            return; // Sai do método sem criar a conta nem fechar a janela
        }
        contabanco.abrirConta(nomeDono, tipoConta); //manda as informações das variaveis armazenadas para a classe principal
        this.novaConta = contabanco; // armazena o objeto 'ContaBanco' recem-criado na variavel de instancia 'novaConta' para que a tela principal possa acessa-lo apos o fechamento dessa tela aq

        //mensagem fofa para mostrar ao usuario que sua conta recebeu um bonus
        if (tipoConta.equals("CP")) {
            JOptionPane.showMessageDialog(this, "Sua conta Conta Poupança recebeu um bonus de R$150,00");
        } else {
            JOptionPane.showMessageDialog(this, "Sua conta Conta Corrente recebeu um bonus de R$50,00");
        }

        this.dispose();//fecha a tela apos criação da conta

    }//GEN-LAST:event_btncriarcontaconfirmarActionPerformed

    private void txtabrircontanomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabrircontanomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabrircontanomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AbrirConta dialog = new AbrirConta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncriarcontaconfirmar;
    private javax.swing.JLabel lblabrircontatipo;
    private javax.swing.JLabel lblinformenome;
    private javax.swing.JTextField txtabrircontanome;
    private javax.swing.JTextField txtabrircontatipo;
    // End of variables declaration//GEN-END:variables
}
