/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.ifba.atividade07.view;

import br.com.ifba.atividade07.classe.ContaBanco;
import javax.swing.JOptionPane;

/**
 *
 * @author dudan
 */
public class Depositar extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Depositar.class.getName());

    // CAMPO CRÍTICO: Guarda a referência do objeto ContaBanco passado pela Tela Principal.
    private ContaBanco contaAtual = null;

    // CONSTRUTOR: Recebe o objeto da conta que vamos operar.
    public Depositar(java.awt.Frame parent, boolean modal, ContaBanco conta) {
        super(parent, modal);
        this.contaAtual = conta; // Guarda o objeto REAL da conta (passado por referência)
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndepositar = new javax.swing.JButton();
        lblvaloradepositar = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btndepositar.setText("Depositar");
        btndepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositarActionPerformed(evt);
            }
        });

        lblvaloradepositar.setText("Quanto quer depositar?");

        txtvalor.setToolTipText("Valor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(btndepositar)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblvaloradepositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvaloradepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btndepositar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Lógica do botão "Depositar"
    private void btndepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositarActionPerformed

        // Uso o try-catch para garantir que o programa não trave se o usuário digitar algo errado (letras, etc.)
        try {
            // 1. Tenta converter o texto digitado (do campo txtvalor) em um número decimal
            double valor = Double.parseDouble(txtvalor.getText());

            // 2. Validação de segurança: Não deixo depositar valor zero ou negativo
            if (valor <= 0) {
                JOptionPane.showMessageDialog(this, "O valor do depósito deve ser positivo.", "Erro de Valor", JOptionPane.WARNING_MESSAGE);
                return; // Se der erro de valor, paro o método e a janela fica aberta para o usuário corrigir
            }

            // 3. Executo a operação na classe de negócio (ContaBanco). 
            // Como contaAtual é uma referência, o saldo do objeto original é alterado.
            contaAtual.depositar(valor);

            // 4. Mensagem de Sucesso
            JOptionPane.showMessageDialog(this, "Depósito de R$ " + String.format("%.2f", valor) + " realizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            this.dispose(); // SÓ FECHA A JANELA APÓS TUDO DAR CERTO!

        } catch (NumberFormatException ex) {
            // Pega o erro se o texto do campo não for um número válido
            JOptionPane.showMessageDialog(this, "Valor inválido. Digite um número decimal.", "Erro de Entrada", JOptionPane.ERROR_MESSAGE);
            // A janela permanece aberta para o usuário tentar de novo
        }
    }//GEN-LAST:event_btndepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Depositar dialog = new Depositar(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndepositar;
    private javax.swing.JLabel lblvaloradepositar;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
